"""AP Invoice Triage Agent (Plain Python -- no LangGraph)
======================================================

A production-ready pipeline that triages AP invoices using the SAP Document AI
(Document Information Extraction) mock APIs generated by the SACC project,
plus the Supplier Invoice OData mock API.

Workflow (11 steps):
    1.  START -> upload document (real PDF bytes via base64 to Files entity)
    2.  Call Document API to get extraction results for classification
    3.  Determine Document Type using shared keywords from keywords.json
        (Invoice, Credit Note, Supporting Document, Statement of Account,
         Reconciliation, Purchase Order List, General Correspondence)
    4.  If not invoice/credit_note/statement -> REVIEW / END
    5.  Classify company: Saudia Cargo vs Saudia Airline
        - Saudia Airline if PO number starts with '62' AND vendor number
          starts with '15' (checked first, returns early)
        - Otherwise Saudia Cargo
    6.  If company does not match -> REVIEW
    7.  Determine DIRECT vs INTERCOMPANY
    8.  Determine invoice type: FUEL | CHARTER | SERVICE | OTHER
    9.  Extract detailed header fields and line items
    10. Validate extraction confidence / required fields
    11. Build and return TriageResult

All API URLs, credentials, company config, and model config
are read from environment variables (see .env.example).

Shared document type categories are loaded from
langgraph/document_types.json — single source of truth used by both
EmailIntakeAgent and TriageAgent.
"""

from __future__ import annotations

import json
import logging
import os
import re
import uuid
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Any, Optional

import httpx

# ── Logging ──────────────────────────────────────────────────────────────────

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
logger = logging.getLogger("triage_agent")

# ── Configuration (all from environment variables) ───────────────────────────

API_BASE_URL = os.getenv("SACC_API_BASE_URL", "http://localhost:8000")

# SAP Document AI real API credentials (TODO: fill in for production)
SAP_DOCAI_BASE_URL = os.getenv("SAP_DOCAI_BASE_URL", "")
SAP_DOCAI_CLIENT_ID = os.getenv("SAP_DOCAI_CLIENT_ID", "")
SAP_DOCAI_CLIENT_SECRET = os.getenv("SAP_DOCAI_CLIENT_SECRET", "")
SAP_DOCAI_AUTH_URL = os.getenv("SAP_DOCAI_AUTH_URL", "")
SAP_DOCAI_TOKEN: Optional[str] = None

# Company configuration
CONFIGURED_COMPANY_CODE = os.getenv("CONFIGURED_COMPANY_CODE", "1000")
CONFIGURED_COMPANY_NAME = os.getenv("CONFIGURED_COMPANY_NAME", "SACC Airlines")
CONFIGURED_COMPANY_VAT = os.getenv("CONFIGURED_COMPANY_VAT", "")
CONFIGURED_COMPANY_TAX_IDS = [
    tid.strip()
    for tid in os.getenv("CONFIGURED_COMPANY_TAX_IDS", "").split(",")
    if tid.strip()
]

# Intercompany company codes (comma-separated)
INTERCOMPANY_COMPANY_CODES = [
    code.strip()
    for code in os.getenv("INTERCOMPANY_COMPANY_CODES", "2000,3000").split(",")
    if code.strip()
]

# Confidence thresholds
MIN_CONFIDENCE_THRESHOLD = float(os.getenv("MIN_CONFIDENCE_THRESHOLD", "0.75"))
MIN_REQUIRED_FIELD_CONFIDENCE = float(
    os.getenv("MIN_REQUIRED_FIELD_CONFIDENCE", "0.80")
)

# Model configuration (for LLM-based classification if needed)
LLM_MODEL_NAME = os.getenv("LLM_MODEL_NAME", "gpt-4")
LLM_API_KEY = os.getenv("LLM_API_KEY", "")
LLM_BASE_URL = os.getenv("LLM_BASE_URL", "")

# Service names in the SACC mock API
DOC_AI_SERVICE = "document_information_extraction_api_v2"
SUPPLIER_INVOICE_SERVICE = "OP_API_SUPPLIERINVOICE_PROCESS_SRV"

# ── Temp: temp_input folder for saving uploaded documents ──────────────────
# TEMP CODE: Save uploaded document info to temp_input folder after upload.
# Combined with using the seeded DocumentVersion from the Get Document API,
# this prevents document_type from defaulting to "OTHER".
# Remove this once the mock API or real SAP Document AI can process uploaded
# files and return real extraction results.
_TEMP_INPUT_DIR = Path(__file__).resolve().parent.parent / "temp_input"


# -- Enums -------------------------------------------------------------------


class DocumentType(str, Enum):
    INVOICE = "INVOICE"
    CREDIT_NOTE = "CREDIT_NOTE"
    STATEMENT = "STATEMENT"
    SUPPORTING_DOCUMENT = "SUPPORTING_DOCUMENT"
    OTHER = "OTHER"


class CompanyClassification(str, Enum):
    MATCH = "MATCH"
    NO_MATCH = "NO_MATCH"
    UNCERTAIN = "UNCERTAIN"


class DirectIntercompany(str, Enum):
    DIRECT = "DIRECT"
    INTERCOMPANY = "INTERCOMPANY"
    UNKNOWN = "UNKNOWN"


class InvoiceType(str, Enum):
    FUEL = "FUEL"
    CHARTER = "CHARTER"
    SERVICE = "SERVICE"
    OTHER = "OTHER"


# ── Shared document type categories (loaded from document_types.json) ─────
_DOCUMENT_TYPES_FILE = Path(__file__).resolve().parent.parent / "document_types.json"
with open(_DOCUMENT_TYPES_FILE, "r", encoding="utf-8") as _f:
    _DOCUMENT_TYPES_DATA = json.load(_f)

_DOCUMENT_TYPE_CATEGORIES = [
    (item["category"], item["document_type"])
    for item in _DOCUMENT_TYPES_DATA["categories"]
]

# Mapping from email intake categories to TriageAgent DocumentType
_CATEGORY_TO_DOC_TYPE = {
    "Invoice": DocumentType.INVOICE,
    "Credit Note": DocumentType.CREDIT_NOTE,
    "Statement of Account": DocumentType.STATEMENT,
    "Supporting Document": DocumentType.SUPPORTING_DOCUMENT,
}


# -- Data Models -------------------------------------------------------------


@dataclass
class ExtractedField:
    """A single extracted field with confidence score."""
    name: str
    value: Any
    confidence: float = 0.0
    raw_value: Optional[str] = None


@dataclass
class LineItem:
    """A line item extracted from the document."""
    item_number: str = ""
    description: str = ""
    quantity: Optional[float] = None
    unit_price: Optional[float] = None
    total_amount: Optional[float] = None
    gl_account: str = ""
    cost_center: str = ""
    tax_code: str = ""
    confidence: float = 0.0
    raw_data: dict[str, Any] = field(default_factory=dict)


@dataclass
class TriageResult:
    """Strict JSON TriageResult returned at the end of the workflow."""
    document_type: str
    company_classification: str
    direct_intercompany: str
    invoice_type: str
    extracted_header_fields: dict[str, Any]
    line_items: list[dict[str, Any]]
    confidence: float
    evidence: list[str]
    review_required: bool
    review_reason: Optional[str]

    def to_dict(self) -> dict[str, Any]:
        return {
            "document_type": self.document_type,
            "company_classification": self.company_classification,
            "direct_intercompany": self.direct_intercompany,
            "invoice_type": self.invoice_type,
            "extracted_header_fields": self.extracted_header_fields,
            "line_items": self.line_items,
            "confidence": self.confidence,
            "evidence": self.evidence,
            "review_required": self.review_required,
            "review_reason": self.review_reason,
        }

    def to_json(self) -> str:
        return json.dumps(self.to_dict(), indent=2, default=str)


# -- Pipeline State (plain dict) ---------------------------------------------

# TriageState is just a dict[str, Any]. Each step function takes the current
# state dict and returns an updated dict.


class TriageState(dict):
    """Mutable dict subclass used as the pipeline state.

    Acts like a normal dict but with attribute-style access for convenience.
    """
    def __getattr__(self, key: str) -> Any:
        try:
            return self[key]
        except KeyError:
            raise AttributeError(key)

    def __setattr__(self, key: str, value: Any) -> None:
        self[key] = value


# -- API Client: Document Information Extraction -----------------------------


class DocAIApiClient:
    """Client for the Document Information Extraction mock API."""

    def __init__(self, base_url: str = API_BASE_URL):
        self.base_url = base_url.rstrip("/")
        self.service = DOC_AI_SERVICE
        self.client = httpx.Client(timeout=30.0)

    def _url(self, entity_set: str, suffix: str = "") -> str:
        path = f"/api/services/{self.service}/entities/{entity_set}"
        if suffix:
            path += suffix
        return f"{self.base_url}{path}"

    # -- Documents ----------------------------------------------------------

    def create_document(self, payload: dict[str, Any]) -> dict[str, Any]:
        """Create a Document record (Step 1: upload document)."""
        resp = self.client.post(self._url("Documents"), json=payload)
        resp.raise_for_status()
        return resp.json()

    def get_document(self, doc_id: str) -> dict[str, Any]:
        """Read a Document record by ID."""
        resp = self.client.get(self._url("Documents", "/item"), params={"ID": doc_id})
        resp.raise_for_status()
        return resp.json()

    def list_documents(self) -> list[dict[str, Any]]:
        """List all Document records."""
        resp = self.client.get(self._url("Documents"))
        resp.raise_for_status()
        return resp.json()

    def update_document(self, doc_id: str, updates: dict[str, Any]) -> dict[str, Any]:
        """Update a Document record (e.g. set schema_ID, status)."""
        resp = self.client.patch(self._url("Documents", "/item"), params={"ID": doc_id}, json=updates)
        resp.raise_for_status()
        return resp.json()

    # -- Files --------------------------------------------------------------

    def get_file(self, file_id: str) -> dict[str, Any]:
        """Read a File record by ID."""
        resp = self.client.get(self._url("Files", "/item"), params={"ID": file_id})
        resp.raise_for_status()
        return resp.json()

    def upload_file(self, file_name: str, file_content: bytes) -> dict[str, Any]:
        """Upload a file to Document AI via the SACC mock API.

        Sends the actual PDF bytes (base64-encoded) to the Files entity
        via POST.  Requires the SACC mock API to be running and the
        Files entity to be insertable (see EDMX configuration).
        """
        import base64
        file_id = str(uuid.uuid4())
        payload = {
            "ID": file_id,
            "name": file_name,
            "contentBytes": base64.b64encode(file_content).decode("utf-8"),
            "size": len(file_content),
        }
        resp = self.client.post(self._url("Files"), json=payload)
        resp.raise_for_status()
        file_record = resp.json()
        logger.info(
            "File uploaded to mock API: ID=%s, name=%s, size=%d bytes",
            file_record.get("ID"), file_name, len(file_content),
        )
        return file_record

    # -- SchemaVersions ----------------------------------------------------

    def create_schema_version(self, payload: dict[str, Any]) -> dict[str, Any]:
        """Create a SchemaVersion record (Step 2: upload schema)."""
        resp = self.client.post(self._url("SchemaVersions"), json=payload)
        resp.raise_for_status()
        return resp.json()

    def get_schema_version(self, version_id: str) -> dict[str, Any]:
        """Read a SchemaVersion by ID (Step 3/12: load schema)."""
        resp = self.client.get(self._url("SchemaVersions", "/item"), params={"ID": version_id})
        resp.raise_for_status()
        return resp.json()

    def list_schema_versions(self, schema_id: str = "") -> list[dict[str, Any]]:
        """List SchemaVersions, optionally filtered by schema_ID."""
        params: dict[str, Any] = {}
        if schema_id:
            params["schema_ID"] = schema_id
        resp = self.client.get(self._url("SchemaVersions"), params=params)
        resp.raise_for_status()
        return resp.json()

    # -- SchemaEntities ----------------------------------------------------

    def create_schema_entity(self, payload: dict[str, Any]) -> dict[str, Any]:
        """Create a SchemaEntity (field definition within a schema version)."""
        resp = self.client.post(self._url("SchemaEntities"), json=payload)
        resp.raise_for_status()
        return resp.json()

    def list_schema_entities(self, schema_version_id: str = "") -> list[dict[str, Any]]:
        """List SchemaEntities, optionally filtered by schemaVersion_ID."""
        params: dict[str, Any] = {}
        if schema_version_id:
            params["schemaVersion_ID"] = schema_version_id
        resp = self.client.get(self._url("SchemaEntities"), params=params)
        resp.raise_for_status()
        return resp.json()

    # -- DocumentEntities (extraction results) ------------------------------

    def create_document_entity(self, payload: dict[str, Any]) -> dict[str, Any]:
        """Create a DocumentEntity (extracted field result)."""
        resp = self.client.post(self._url("DocumentEntities"), json=payload)
        resp.raise_for_status()
        return resp.json()

    def list_document_entities(self, document_version_id: str = "") -> list[dict[str, Any]]:
        """List DocumentEntities (extraction results)."""
        params: dict[str, Any] = {}
        if document_version_id:
            params["documentVersion_ID"] = document_version_id
        resp = self.client.get(self._url("DocumentEntities"), params=params)
        resp.raise_for_status()
        return resp.json()

    def get_document_entity(self, entity_id: str) -> dict[str, Any]:
        """Read a single DocumentEntity by ID."""
        resp = self.client.get(self._url("DocumentEntities", "/item"), params={"ID": entity_id})
        resp.raise_for_status()
        return resp.json()

    # -- DocumentTypes -----------------------------------------------------

    def list_document_types(self) -> list[dict[str, Any]]:
        """List all DocumentTypes."""
        resp = self.client.get(self._url("DocumentTypes"))
        resp.raise_for_status()
        return resp.json()

    def create_document_type(self, payload: dict[str, Any]) -> dict[str, Any]:
        """Create a DocumentType."""
        resp = self.client.post(self._url("DocumentTypes"), json=payload)
        resp.raise_for_status()
        return resp.json()

    # -- DocumentsVersions -------------------------------------------------

    def create_document_version(self, payload: dict[str, Any]) -> dict[str, Any]:
        """Create a DocumentVersion (version of a processed document)."""
        resp = self.client.post(self._url("DocumentsVersions"), json=payload)
        resp.raise_for_status()
        return resp.json()

    def list_document_versions(self, document_id: str = "") -> list[dict[str, Any]]:
        """List DocumentVersions for a document."""
        params: dict[str, Any] = {}
        if document_id:
            params["document_ID"] = document_id
        resp = self.client.get(self._url("DocumentsVersions"), params=params)
        resp.raise_for_status()
        return resp.json()

    # -- Processing (MISSING -- filler) --------------------------------------

    def trigger_processing(self, document_id: str) -> dict[str, Any]:
        """Trigger document processing.

        TEMP: Instead of creating a new DocumentVersion (which has no seeded
        DocumentEntities), list the existing seeded DocumentVersions from the
        Get Document API and use the first one's ID. This way
        get_extraction_results will find the seeded DocumentEntities and
        document_type won't default to "OTHER".
        """
        # TEMP: Use existing seeded DocumentVersion instead of creating a new one
        versions = self.list_document_versions()
        if versions:
            version_id = versions[0].get("ID", str(uuid.uuid4()))
            logger.info("Using seeded DocumentVersion: %s", version_id)
            return {
                "document_version_id": version_id,
                "status": "COMPLETED",
            }
        # Fallback: create new version if no seeded versions exist
        logger.warning("No seeded DocumentVersions found — creating new one")
        version_id = str(uuid.uuid4())
        self.create_document_version({
            "ID": version_id,
            "document_ID": document_id,
            "version": 1,
        })
        return {
            "document_version_id": version_id,
            "status": "COMPLETED",
        }

    def get_extraction_results(self, document_version_id: str) -> list[dict[str, Any]]:
        """Retrieve extraction results (DocumentEntities) for a document version.

        TEMP: If no entities found for the given version, fall back to listing
        ALL DocumentEntities (the seeded ones) so classification has data to
        work with instead of returning 0 entities and defaulting to "OTHER".
        """
        results = self.list_document_entities(document_version_id)
        if not results:
            # TEMP: Fall back to all seeded DocumentEntities
            results = self.list_document_entities("")
            if results:
                logger.info("Using seeded DocumentEntities (%d entities)", len(results))
            else:
                logger.warning(
                    "No DocumentEntities found at all — seeded data may be missing.",
                )
        return results


# -- API Client: Supplier Invoice ---------------------------------------------


class SupplierInvoiceApiClient:
    """Client for the Supplier Invoice mock API."""

    def __init__(self, base_url: str = API_BASE_URL):
        self.base_url = base_url.rstrip("/")
        self.service = SUPPLIER_INVOICE_SERVICE
        self.client = httpx.Client(timeout=30.0)

    def _url(self, entity_set: str, suffix: str = "") -> str:
        path = f"/api/services/{self.service}/entities/{entity_set}"
        if suffix:
            path += suffix
        return f"{self.base_url}{path}"

    def create_invoice(self, payload: dict[str, Any]) -> dict[str, Any]:
        resp = self.client.post(self._url("A_SupplierInvoice"), json=payload)
        resp.raise_for_status()
        return resp.json()

    def get_invoice(self, supplier_invoice: str, fiscal_year: str) -> dict[str, Any]:
        resp = self.client.get(self._url("A_SupplierInvoice", "/item"), params={
            "SupplierInvoice": supplier_invoice,
            "FiscalYear": fiscal_year,
        })
        resp.raise_for_status()
        return resp.json()

    def list_invoice_items(self, supplier_invoice: str) -> list[dict[str, Any]]:
        resp = self.client.get(self._url("A_SupplierInvoiceItemGLAcct"), params={"SupplierInvoice": supplier_invoice})
        resp.raise_for_status()
        return resp.json()

    def create_invoice_item(self, payload: dict[str, Any]) -> dict[str, Any]:
        """Create a Supplier Invoice line item.

        NOTE: A_SupplierInvoiceItemGLAcct has insertable=false in the mock.
        This will fail against the mock API. In production, use the real SAP API.
        """
        resp = self.client.post(self._url("A_SupplierInvoiceItemGLAcct"), json=payload)
        resp.raise_for_status()
        return resp.json()


# -- Validation Field Definitions -------------------------------------------
# Required field definitions per invoice type (used by validate_extraction).
# These describe which header fields are mandatory for each invoice type.

# Detailed field definitions per invoice type
# Each schema defines header fields and a line_items collection.
# The "children" key in line_items defines the sub-fields for each line item.

_LINE_ITEM_CHILDREN = [
    {"name": "item_description", "label": "Description", "type": "string", "dataType": "string"},
    {"name": "quantity", "label": "Quantity", "type": "number", "dataType": "number"},
    {"name": "unit_price", "label": "Unit Price", "type": "number", "dataType": "number"},
    {"name": "total_amount", "label": "Total", "type": "number", "dataType": "number"},
    {"name": "gl_account", "label": "GL Account", "type": "string", "dataType": "string"},
    {"name": "cost_center", "label": "Cost Center", "type": "string", "dataType": "string"},
    {"name": "tax_code", "label": "Tax Code", "type": "string", "dataType": "string"},
]

_COMMON_HEADER_FIELDS = [
    {"name": "invoice_number", "label": "Invoice Number", "type": "string", "dataType": "string", "mandatory": True, "minimumOccurrence": 1, "maximumOccurrence": 1},
    {"name": "invoice_date", "label": "Invoice Date", "type": "date", "dataType": "date", "mandatory": True, "minimumOccurrence": 1, "maximumOccurrence": 1},
    {"name": "supplier_name", "label": "Supplier Name", "type": "string", "dataType": "string", "mandatory": True, "minimumOccurrence": 1, "maximumOccurrence": 1},
    {"name": "company_code", "label": "Company Code", "type": "string", "dataType": "string", "mandatory": True, "minimumOccurrence": 1, "maximumOccurrence": 1},
    {"name": "total_amount", "label": "Total Amount", "type": "number", "dataType": "number", "mandatory": True, "minimumOccurrence": 1, "maximumOccurrence": 1},
    {"name": "currency", "label": "Currency", "type": "string", "dataType": "string", "mandatory": True, "minimumOccurrence": 1, "maximumOccurrence": 1},
    {"name": "tax_amount", "label": "Tax Amount", "type": "number", "dataType": "number", "mandatory": False, "minimumOccurrence": 0, "maximumOccurrence": 1},
    {"name": "net_amount", "label": "Net Amount", "type": "number", "dataType": "number", "mandatory": False, "minimumOccurrence": 0, "maximumOccurrence": 1},
]


def _line_items_entity() -> dict[str, Any]:
    return {
        "name": "line_items", "label": "Line Items",
        "type": "collection", "dataType": "collection",
        "mandatory": False, "minimumOccurrence": 0, "maximumOccurrence": 100,
        "children": _LINE_ITEM_CHILDREN,
    }


DETAILED_SCHEMAS: dict[str, list[dict[str, Any]]] = {
    InvoiceType.FUEL.value: _COMMON_HEADER_FIELDS + [
        {"name": "fuel_type", "label": "Fuel Type", "type": "string", "dataType": "string", "mandatory": True, "minimumOccurrence": 1, "maximumOccurrence": 1},
        {"name": "fuel_quantity", "label": "Fuel Quantity", "type": "number", "dataType": "number", "mandatory": True, "minimumOccurrence": 1, "maximumOccurrence": 1},
        {"name": "fuel_unit", "label": "Fuel Unit", "type": "string", "dataType": "string", "mandatory": False, "minimumOccurrence": 0, "maximumOccurrence": 1},
        {"name": "unit_price", "label": "Unit Price", "type": "number", "dataType": "number", "mandatory": True, "minimumOccurrence": 1, "maximumOccurrence": 1},
        {"name": "airport_code", "label": "Airport Code", "type": "string", "dataType": "string", "mandatory": False, "minimumOccurrence": 0, "maximumOccurrence": 1},
        {"name": "flight_number", "label": "Flight Number", "type": "string", "dataType": "string", "mandatory": False, "minimumOccurrence": 0, "maximumOccurrence": 1},
        _line_items_entity(),
    ],
    InvoiceType.CHARTER.value: _COMMON_HEADER_FIELDS + [
        {"name": "charter_type", "label": "Charter Type", "type": "string", "dataType": "string", "mandatory": True, "minimumOccurrence": 1, "maximumOccurrence": 1},
        {"name": "aircraft_registration", "label": "Aircraft Registration", "type": "string", "dataType": "string", "mandatory": False, "minimumOccurrence": 0, "maximumOccurrence": 1},
        {"name": "flight_route_from", "label": "Route From", "type": "string", "dataType": "string", "mandatory": False, "minimumOccurrence": 0, "maximumOccurrence": 1},
        {"name": "flight_route_to", "label": "Route To", "type": "string", "dataType": "string", "mandatory": False, "minimumOccurrence": 0, "maximumOccurrence": 1},
        {"name": "flight_date", "label": "Flight Date", "type": "date", "dataType": "date", "mandatory": False, "minimumOccurrence": 0, "maximumOccurrence": 1},
        {"name": "passenger_count", "label": "Passenger Count", "type": "number", "dataType": "number", "mandatory": False, "minimumOccurrence": 0, "maximumOccurrence": 1},
        _line_items_entity(),
    ],
    InvoiceType.SERVICE.value: _COMMON_HEADER_FIELDS + [
        {"name": "service_type", "label": "Service Type", "type": "string", "dataType": "string", "mandatory": True, "minimumOccurrence": 1, "maximumOccurrence": 1},
        {"name": "service_period_start", "label": "Service Period Start", "type": "date", "dataType": "date", "mandatory": False, "minimumOccurrence": 0, "maximumOccurrence": 1},
        {"name": "service_period_end", "label": "Service Period End", "type": "date", "dataType": "date", "mandatory": False, "minimumOccurrence": 0, "maximumOccurrence": 1},
        {"name": "purchase_order_number", "label": "PO Number", "type": "string", "dataType": "string", "mandatory": False, "minimumOccurrence": 0, "maximumOccurrence": 1},
        _line_items_entity(),
    ],
    InvoiceType.OTHER.value: _COMMON_HEADER_FIELDS + [
        _line_items_entity(),
    ],
}


# -- Pipeline Step Functions ------------------------------------------------

# Global API client instances (lazily initialised)
_doc_ai_client: Optional[DocAIApiClient] = None
_supplier_invoice_client: Optional[SupplierInvoiceApiClient] = None


def _get_doc_ai_client() -> DocAIApiClient:
    global _doc_ai_client
    if _doc_ai_client is None:
        _doc_ai_client = DocAIApiClient()
    return _doc_ai_client


def _get_supplier_invoice_client() -> SupplierInvoiceApiClient:
    global _supplier_invoice_client
    if _supplier_invoice_client is None:
        _supplier_invoice_client = SupplierInvoiceApiClient()
    return _supplier_invoice_client


def _extract_value(entity: dict[str, Any]) -> str:
    """Extract the string value from a DocumentEntity record."""
    return (
        entity.get("stringValue")
        or str(entity.get("numberValue", "") or "")
        or entity.get("dateValue", "")
        or entity.get("rawValue", "")
        or ""
    )


def _build_lookup(extraction: list[dict[str, Any]]) -> dict[str, str]:
    """Build a name->value lookup from a list of DocumentEntity records."""
    lookup: dict[str, str] = {}
    for entity in extraction:
        name = entity.get("name", "")
        value = _extract_value(entity)
        if name and value:
            lookup[name] = str(value)
    return lookup


# -- Step 1: Upload Document --------------------------------------------------

def upload_document(state: TriageState) -> TriageState:
    """Upload the source document file to Document AI."""
    logger.info("Step 1: Uploading document...")
    file_path = state.get("file_path", "")
    file_name = state.get("file_name", "")
    evidence = state.get("evidence", [])

    client = _get_doc_ai_client()

    # Read file content if path is provided
    file_content = None
    if file_path and os.path.isfile(file_path):
        with open(file_path, "rb") as f:
            file_content = f.read()
        if not file_name:
            file_name = os.path.basename(file_path)
        evidence.append(f"File loaded from disk: {file_name} ({len(file_content)} bytes)")
    elif not file_name:
        file_name = "unknown_document.pdf"
        evidence.append("No file path provided -- using placeholder name")

    # Upload file to mock API
    file_record = client.upload_file(file_name, file_content or b"")
    file_id = file_record.get("ID", str(uuid.uuid4()))

    # Create Document record
    doc_id = str(uuid.uuid4())
    client.create_document({
        "ID": doc_id,
        "status": "PENDING",
        "file_ID": file_id,
        "clientId": SAP_DOCAI_CLIENT_ID,
    })

    # TEMP: Save uploaded document info to temp_input folder
    _TEMP_INPUT_DIR.mkdir(parents=True, exist_ok=True)
    _temp_doc_path = _TEMP_INPUT_DIR / f"{doc_id}.json"
    with open(_temp_doc_path, "w", encoding="utf-8") as f:
        json.dump({
            "document_id": doc_id,
            "file_id": file_id,
            "file_name": file_name,
            "file_size": len(file_content) if file_content else 0,
        }, f, indent=2)
    logger.info("Saved document info to temp_input: %s", _temp_doc_path.name)

    evidence.append(f"Document created with ID={doc_id}, file_ID={file_id}")
    logger.info("Document uploaded: ID=%s", doc_id)

    return {**state, "document_id": doc_id, "file_id": file_id,
            "file_name": file_name, "evidence": evidence}


# -- Step 2: Call Document API for Extraction -------------------------------

def classify_with_document_api(state: TriageState) -> TriageState:
    """Call Document API to get initial extraction results for classification."""
    logger.info("Step 2: Calling Document API...")
    evidence = state.get("evidence", [])
    doc_id = state.get("document_id", "")
    client = _get_doc_ai_client()

    # Update the Document record to trigger processing
    client.update_document(doc_id, {"status": "PROCESSING"})

    # Trigger processing (mocked -- see DocAIApiClient.trigger_processing)
    processing_result = client.trigger_processing(doc_id)
    doc_version_id = processing_result.get("document_version_id", str(uuid.uuid4()))

    # Retrieve extraction results
    extraction_results = client.get_extraction_results(doc_version_id)

    evidence.append(f"Document API called. "
                    f"Document version: {doc_version_id}, "
                    f"extraction results: {len(extraction_results)} entities")
    logger.info("Extraction results: %d entities", len(extraction_results))
    return {**state, "document_version_id": doc_version_id,
            "classification_extraction": extraction_results, "evidence": evidence}


# -- Step 3: Determine Document Type -----------------------------------------

def determine_document_type(state: TriageState) -> TriageState:
    """Determine the document type from classification extraction results.

    Uses the shared document type categories from document_types.json to classify the
    document as INVOICE, CREDIT_NOTE, STATEMENT, SUPPORTING_DOCUMENT, or OTHER.
    """
    logger.info("Step 3: Determining document type...")
    evidence = state.get("evidence", [])
    extraction = state.get("classification_extraction", [])
    extracted_values = _build_lookup(extraction)

    # Lowercase all values for matching
    all_text = " ".join(v.lower() for v in extracted_values.values())
    doc_type_field = extracted_values.get("document_type", "").lower()

    doc_type = DocumentType.OTHER

    # Check explicit document_type field first, then fall back to all text
    search_text = doc_type_field if doc_type_field else all_text
    for category, doc_types in _DOCUMENT_TYPE_CATEGORIES:
        mapped_type = _CATEGORY_TO_DOC_TYPE.get(category)
        if mapped_type and any(kw in search_text for kw in doc_types):
            doc_type = mapped_type
            break

    evidence.append(f"Document type determined: {doc_type.value} (based on shared document types from document_types.json)")
    logger.info("Document type: %s", doc_type.value)
    return {**state, "document_type": doc_type.value, "evidence": evidence}


# -- Step 5: Classify Company -------------------------------------------------

def classify_company(state: TriageState) -> TriageState:
    """Classify whether the document belongs to the configured fixed company."""
    logger.info("Step 5: Classifying company...")
    evidence = state.get("evidence", [])
    extraction = state.get("classification_extraction", [])
    extracted_values = _build_lookup(extraction)

    extracted_company_code = extracted_values.get("company_code", "").strip()
    extracted_company_name = extracted_values.get("company_name", "").strip().lower()

    company_classification = CompanyClassification.UNCERTAIN
    match_reasons: list[str] = []

    # Check if this is a Saudia Airline invoice (not Saudia Cargo)
    # If PO number starts with 62 and vendor number starts with 15,
    # the invoice belongs to Saudia Airline, not Saudia Cargo.
    po_number = (
        extracted_values.get("purchase_order_number", "")
        or extracted_values.get("po_number", "")
    ).strip()
    vendor_number = (
        extracted_values.get("vendor_number", "")
        or extracted_values.get("supplier_number", "")
    ).strip()

    if po_number.startswith("62") and vendor_number.startswith("15"):
        company_classification = CompanyClassification.MATCH
        match_reasons.append(
            f"Saudia Airline invoice (PO '{po_number}' starts with 62, "
            f"vendor '{vendor_number}' starts with 15) — not Saudia Cargo"
        )
        evidence.append("Company identified as Saudia Airline (not Saudia Cargo)")
        logger.info("Company classification: %s (Saudia Airline)", company_classification.value)
        return {**state, "company_classification": company_classification.value,
                "company_name": "Saudia Airline", "evidence": evidence}

    if extracted_company_code:
        if extracted_company_code == CONFIGURED_COMPANY_CODE:
            company_classification = CompanyClassification.MATCH
            match_reasons.append(f"Company code '{extracted_company_code}' matches configured '{CONFIGURED_COMPANY_CODE}'")
        elif extracted_company_code in INTERCOMPANY_COMPANY_CODES:
            company_classification = CompanyClassification.MATCH
            match_reasons.append(f"Company code '{extracted_company_code}' is an intercompany code")
        else:
            company_classification = CompanyClassification.NO_MATCH
            match_reasons.append(f"Company code '{extracted_company_code}' does not match configured '{CONFIGURED_COMPANY_CODE}'")

    if extracted_company_name and CONFIGURED_COMPANY_NAME:
        configured_name = CONFIGURED_COMPANY_NAME.lower()
        if configured_name in extracted_company_name or extracted_company_name in configured_name:
            if company_classification != CompanyClassification.NO_MATCH:
                company_classification = CompanyClassification.MATCH
            match_reasons.append(f"Company name matches configured '{CONFIGURED_COMPANY_NAME}'")
        else:
            if not extracted_company_code:
                company_classification = CompanyClassification.NO_MATCH
                match_reasons.append(f"Company name does not match configured '{CONFIGURED_COMPANY_NAME}'")

    if not extracted_company_code and not extracted_company_name:
        company_classification = CompanyClassification.UNCERTAIN
        match_reasons.append("No company code or name extracted -- classification uncertain")

    evidence.append(f"Company classification: {company_classification.value}. " + "; ".join(match_reasons))
    logger.info("Company classification: %s", company_classification.value)
    return {**state, "company_classification": company_classification.value, "evidence": evidence}


# -- Step 7: Determine DIRECT vs INTERCOMPANY ---------------------------------

def classify_direct_intercompany(state: TriageState) -> TriageState:
    """Determine whether the invoice is DIRECT or INTERCOMPANY.

    Business rules:
    - If the extracted company code matches the configured company code -> DIRECT
    - If the extracted company code is in the intercompany list -> INTERCOMPANY
    - Otherwise -> UNKNOWN (requires review)
    """
    logger.info("Step 7: Determining DIRECT vs INTERCOMPANY...")
    evidence = state.get("evidence", [])
    extraction = state.get("classification_extraction", [])
    extracted_values = _build_lookup(extraction)

    extracted_company_code = extracted_values.get("company_code", "")
    extracted_supplier_name = extracted_values.get("supplier_name", "").lower()

    classification = DirectIntercompany.UNKNOWN
    reasons: list[str] = []

    if extracted_company_code == CONFIGURED_COMPANY_CODE:
        classification = DirectIntercompany.DIRECT
        reasons.append(f"Company code matches configured company -- DIRECT")
    elif extracted_company_code in INTERCOMPANY_COMPANY_CODES:
        classification = DirectIntercompany.INTERCOMPANY
        reasons.append(f"Company code is in intercompany list -- INTERCOMPANY")
    else:
        configured_name = CONFIGURED_COMPANY_NAME.lower()
        if extracted_supplier_name and configured_name:
            if configured_name in extracted_supplier_name or extracted_supplier_name in configured_name:
                classification = DirectIntercompany.INTERCOMPANY
                reasons.append("Supplier name matches intercompany pattern -- INTERCOMPANY")
            else:
                reasons.append("Cannot determine DIRECT vs INTERCOMPANY from available evidence")
        else:
            reasons.append("Insufficient evidence to determine DIRECT vs INTERCOMPANY")

    evidence.append(f"Direct/Intercompany: {classification.value}. " + "; ".join(reasons))
    logger.info("Direct/Intercompany: %s", classification.value)
    return {**state, "direct_intercompany": classification.value, "evidence": evidence}


# -- Step 8: Determine Invoice Type ------------------------------------------

def classify_invoice_type(state: TriageState) -> TriageState:
    """Determine the invoice type: FUEL, CHARTER, SERVICE, or OTHER.

    Uses keyword matching on extracted text, document title, and keywords.
    """
    logger.info("Step 8: Determining invoice type...")
    evidence = state.get("evidence", [])
    extraction = state.get("classification_extraction", [])
    extracted_values = _build_lookup(extraction)

    all_text = " ".join(v.lower() for v in extracted_values.values())
    keywords = extracted_values.get("keywords", "").lower()
    combined = f"{all_text} {keywords}"

    invoice_type = InvoiceType.OTHER
    reasons: list[str] = []

    fuel_keywords = ["fuel", "jet fuel", "avgas", "jet-a", "jet a1", "aviation fuel",
                     "fuel surcharge", "gallons", "litres", "uplift", "into-plane", "fueling", "refuel"]
    if any(kw in combined for kw in fuel_keywords):
        invoice_type = InvoiceType.FUEL
        reasons.append("Fuel keywords detected in extracted text")

    charter_keywords = ["charter", "acmi", "wet lease", "dry lease", "aircraft charter",
                        "charter flight", "private flight", "air taxi"]
    if invoice_type == InvoiceType.OTHER and any(kw in combined for kw in charter_keywords):
        invoice_type = InvoiceType.CHARTER
        reasons.append("Charter keywords detected in extracted text")

    service_keywords = ["service", "maintenance", "repair", "overhaul", "mro",
                        "ground handling", "catering", "cleaning", "consulting",
                        "professional services", "facility"]
    if invoice_type == InvoiceType.OTHER and any(kw in combined for kw in service_keywords):
        invoice_type = InvoiceType.SERVICE
        reasons.append("Service keywords detected in extracted text")

    if invoice_type == InvoiceType.OTHER:
        reasons.append("No specific invoice type keywords detected -- classified as OTHER")

    evidence.append(f"Invoice type: {invoice_type.value}. " + "; ".join(reasons))
    logger.info("Invoice type: %s", invoice_type.value)
    return {**state, "invoice_type": invoice_type.value, "evidence": evidence}


# -- Step 9: Extract Detailed Fields -----------------------------------------

def extract_detailed_fields(state: TriageState) -> TriageState:
    """Call Document API again to extract header fields and line items."""
    logger.info("Step 9: Extracting detailed fields...")
    evidence = state.get("evidence", [])
    doc_id = state.get("document_id", "")
    client = _get_doc_ai_client()

    # Update document status to trigger processing
    client.update_document(doc_id, {"status": "PROCESSING"})

    # Trigger processing (mocked)
    processing_result = client.trigger_processing(doc_id)
    doc_version_id = processing_result.get("document_version_id", str(uuid.uuid4()))

    # Retrieve extraction results
    detailed_extraction = client.get_extraction_results(doc_version_id)

    # Parse extracted entities into header fields and line items
    header_fields: dict[str, Any] = {}
    field_confidences: dict[str, float] = {}
    line_items: list[dict[str, Any]] = []

    for entity in detailed_extraction:
        name = entity.get("name", "")
        confidence = float(entity.get("confidence", 0.0) or 0.0)
        value = _extract_value(entity)
        if not name:
            continue
        if name == "line_items" or entity.get("type") == "collection":
            continue
        header_fields[name] = value
        field_confidences[name] = confidence

    # NOTE: Line items extraction would require parsing child DocumentEntities
    # with parent_ID relationships. In the mock, we simulate this.
    # TODO: When using real SAP Document AI, parse child entities from the
    # DocumentEntities collection where parent_ID points to a line_items entity.
    if not line_items and header_fields.get("total_amount"):
        line_items.append({
            "item_number": "00001",
            "description": header_fields.get("invoice_number", "Line item 1"),
            "quantity": 1,
            "unit_price": float(header_fields.get("total_amount", 0) or 0),
            "total_amount": float(header_fields.get("total_amount", 0) or 0),
            "gl_account": "", "cost_center": "", "tax_code": "",
            "confidence": 0.0,
        })

    evidence.append(f"Detailed extraction complete: {len(header_fields)} header fields, "
                    f"{len(line_items)} line items")
    logger.info("Detailed extraction: %d header fields, %d line items",
                len(header_fields), len(line_items))
    return {**state, "detailed_extraction": detailed_extraction,
            "header_fields": header_fields, "field_confidences": field_confidences,
            "line_items": line_items, "evidence": evidence}


# -- Step 10: Validate Extraction ---------------------------------------------

def validate_extraction(state: TriageState) -> TriageState:
    """Validate extraction confidence and required fields."""
    logger.info("Step 10: Validating extraction...")
    evidence = state.get("evidence", [])
    invoice_type = state.get("invoice_type", InvoiceType.OTHER.value)
    header_fields = state.get("header_fields", {})
    field_confidences = state.get("field_confidences", {})
    line_items = state.get("line_items", [])

    # Get required fields from the validation field definitions
    schema_entities = DETAILED_SCHEMAS.get(invoice_type, DETAILED_SCHEMAS[InvoiceType.OTHER.value])
    required_fields = [e["name"] for e in schema_entities
                       if e.get("mandatory") and e.get("type") != "collection"]

    missing_required = [f for f in required_fields if f not in header_fields or not header_fields[f]]
    low_confidence = [f for f, conf in field_confidences.items()
                      if conf < MIN_REQUIRED_FIELD_CONFIDENCE and f in required_fields]

    if field_confidences:
        overall_confidence = sum(field_confidences.values()) / len(field_confidences)
    else:
        overall_confidence = 0.0

    review_reasons: list[str] = []
    if missing_required:
        review_reasons.append(f"Missing required fields: {', '.join(missing_required)}")
    if low_confidence:
        review_reasons.append(f"Low confidence on required fields: {', '.join(low_confidence)}")
    if overall_confidence < MIN_CONFIDENCE_THRESHOLD:
        review_reasons.append(f"Overall confidence {overall_confidence:.2f} below threshold {MIN_CONFIDENCE_THRESHOLD}")
    if not line_items:
        review_reasons.append("No line items extracted")
    if state.get("direct_intercompany") == DirectIntercompany.UNKNOWN.value:
        review_reasons.append("DIRECT vs INTERCOMPANY could not be determined")

    review_required = len(review_reasons) > 0
    review_reason = "; ".join(review_reasons) if review_reasons else None

    evidence.append(f"Validation: confidence={overall_confidence:.2f}, "
                    f"missing={len(missing_required)}, low_conf={len(low_confidence)}, "
                    f"review_required={review_required}")
    if review_required:
        evidence.append(f"Review reason: {review_reason}")
    logger.info("Validation: confidence=%.2f, review_required=%s", overall_confidence, review_required)
    return {**state, "confidence": overall_confidence,
            "missing_required_fields": missing_required,
            "low_confidence_fields": low_confidence,
            "review_required": review_required,
            "review_reason": review_reason, "evidence": evidence}


# -- Step 11: Build Triage Result ---------------------------------------------

def build_triage_result(state: TriageState) -> TriageState:
    """Build and return the strict JSON TriageResult."""
    logger.info("Step 11: Building TriageResult...")
    result = TriageResult(
        document_type=state.get("document_type", DocumentType.OTHER.value),
        company_classification=state.get("company_classification", CompanyClassification.UNCERTAIN.value),
        direct_intercompany=state.get("direct_intercompany", DirectIntercompany.UNKNOWN.value),
        invoice_type=state.get("invoice_type", InvoiceType.OTHER.value),
        extracted_header_fields=state.get("header_fields", {}),
        line_items=state.get("line_items", []),
        confidence=state.get("confidence", 0.0),
        evidence=state.get("evidence", []),
        review_required=state.get("review_required", True),
        review_reason=state.get("review_reason"),
    )
    result_dict = result.to_dict()
    logger.info("TriageResult:\n%s", result.to_json())
    return {**state, "triage_result": result_dict}


# -- Review Node (for documents that need manual review) ----------------------

def review_node(state: TriageState) -> TriageState:
    """Handle documents that require manual review."""
    logger.info("Routing to REVIEW...")
    evidence = state.get("evidence", [])
    doc_type = state.get("document_type", DocumentType.OTHER.value)

    reason = f"Document type '{doc_type}' is not a valid AP document (INVOICE/CREDIT_NOTE/STATEMENT)"
    if state.get("company_classification") == CompanyClassification.NO_MATCH.value:
        reason = f"Company does not match configured company '{CONFIGURED_COMPANY_NAME}' ({CONFIGURED_COMPANY_CODE})"

    evidence.append(f"Review required: {reason}")
    result = TriageResult(
        document_type=doc_type,
        company_classification=state.get("company_classification", CompanyClassification.UNCERTAIN.value),
        direct_intercompany=state.get("direct_intercompany", DirectIntercompany.UNKNOWN.value),
        invoice_type=state.get("invoice_type", InvoiceType.OTHER.value),
        extracted_header_fields=state.get("header_fields", {}),
        line_items=state.get("line_items", []),
        confidence=state.get("confidence", 0.0),
        evidence=evidence, review_required=True, review_reason=reason,
    )
    return {**state, "review_required": True, "review_reason": reason,
            "triage_result": result.to_dict(), "evidence": evidence}


# -- Plain Python Pipeline (no LangGraph) ------------------------------------


# Valid AP document types for Step 6 branching
_VALID_AP_TYPES = {
    DocumentType.INVOICE.value,
    DocumentType.CREDIT_NOTE.value,
    DocumentType.STATEMENT.value,
}


def run_triage(file_path: str = "", file_name: str = "") -> dict[str, Any]:
    """Run the triage pipeline on a single document.

    This is a plain sequential function chain with two if/else branches:
      - Step 6: document type not valid -> review -> build result -> return
      - Step 8: company no match -> review -> build result -> return
    No StateGraph or conditional edges needed.

    Args:
        file_path: Path to the document file to triage.
        file_name: Override file name (used if file_path is empty).

    Returns:
        The TriageResult as a dict.
    """
    # -- Initialise state --------------------------------------------------
    state: TriageState = TriageState(
        file_path=file_path,
        file_name=file_name or (os.path.basename(file_path) if file_path else ""),
        file_content=None,
        errors=[],
        evidence=[],
        header_fields={},
        line_items=[],
        field_confidences={},
        missing_required_fields=[],
        low_confidence_fields=[],
        review_required=False,
        review_reason=None,
        confidence=0.0,
    )

    # -- Steps 1-3: Upload & classify (always run) ------------------------
    state = upload_document(state)
    state = classify_with_document_api(state)
    state = determine_document_type(state)

    # -- Step 4: Branch on document type -----------------------------------
    if state.get("document_type", DocumentType.OTHER.value) not in _VALID_AP_TYPES:
        logger.info("Step 4: Document type not valid AP -> review")
        state = review_node(state)
        state = build_triage_result(state)
        return state.get("triage_result", {})

    # -- Step 5: Classify company ------------------------------------------
    state = classify_company(state)

    # -- Step 6: Branch on company classification ---------------------------
    if state.get("company_classification") == CompanyClassification.NO_MATCH.value:
        logger.info("Step 6: Company no match -> review")
        state = review_node(state)
        state = build_triage_result(state)
        return state.get("triage_result", {})

    # -- Steps 7-8, 9-10: Extraction pipeline for valid AP documents ----
    state = classify_direct_intercompany(state)
    state = classify_invoice_type(state)
    state = extract_detailed_fields(state)
    state = validate_extraction(state)

    # -- Step 11: Build final result ---------------------------------------
    state = build_triage_result(state)
    return state.get("triage_result", {})


def check_posted_documents() -> None:
    """List all posted documents with their versions and extraction entities."""
    client = _get_doc_ai_client()

    docs = client.list_documents()
    if not docs:
        print("No documents posted to the mock API.")
        return

    print(f"\n{'=' * 80}")
    print(f"POSTED DOCUMENTS ({len(docs)} total)")
    print(f"{'=' * 80}")

    for doc in docs:
        doc_id = doc.get("ID", "")
        status = doc.get("status", "")
        file_id = doc.get("file_ID", "")
        print(f"\n--- Document ID: {doc_id}")
        print(f"    Status:    {status}")
        print(f"    File ID:   {file_id}")

        # List versions for this document
        versions = client.list_document_versions(doc_id)
        if versions:
            for ver in versions:
                ver_id = ver.get("ID", "")
                ver_num = ver.get("version", "")
                print(f"    Version:   {ver_num} (ID: {ver_id})")

                # List extraction entities for this version
                entities = client.get_extraction_results(ver_id)
                if entities:
                    print(f"    Entities:  {len(entities)} extraction results")
                    for ent in entities:
                        name = ent.get("name", "")
                        value = _extract_value(ent)
                        conf = ent.get("confidence", "")
                        print(f"      - {name}: {value}  (confidence: {conf})")
                else:
                    print(f"    Entities:  none")
        else:
            print(f"    Versions:  none")

    print(f"\n{'=' * 80}\n")


def main():
    """CLI entry point."""
    import sys
    file_path = ""
    if len(sys.argv) > 1:
        file_path = sys.argv[1]

    if file_path == "--check":
        check_posted_documents()
        return

    if not file_path:
        print("Usage: python triage_agent.py <file_path>")
        print("\nRunning with no file (will use mock/placeholder)...")
    result = run_triage(file_path=file_path)
    print("\n" + "=" * 80)
    print("TRIAGE RESULT")
    print("=" * 80)
    print(json.dumps(result, indent=2, default=str))


if __name__ == "__main__":
    main()